// @generated by scripts/optimize-art.mjs — do not edit by hand.
// Maps original art filenames to optimized public assets.
export const artImageMap: Record<string, string> = {
  "illustrations/02-palasi.png": "/art-optimized/illustrations/02-palasi.webp",
  "illustrations/03-taojinniang.png": "/art-optimized/illustrations/03-taojinniang.webp",
  "illustrations/08-pepe.png": "/art-optimized/illustrations/08-pepe.webp",
  "product-posters/05-powerdrill-variant.png": "/art-optimized/product-posters/05-powerdrill-variant.webp",
  "product-posters/06-zoem-bike.png": "/art-optimized/product-posters/06-zoem-bike.webp",
  "product-posters/07-zoem-bike-variant.png": "/art-optimized/product-posters/07-zoem-bike-variant.webp",
  "fashion-design/01-ibuki-suika.png": "/art-optimized/fashion-design/01-ibuki-suika.webp",
  "fashion-design/02-ibuki-suika.png": "/art-optimized/fashion-design/02-ibuki-suika.webp",
  "fashion-design/04-ibuki-suika.png": "/art-optimized/fashion-design/04-ibuki-suika.webp",
  "food-art/01-seven-color-yokan.png": "/art-optimized/food-art/01-seven-color-yokan.webp",
  "food-art/02-niten-ichiryu.png": "/art-optimized/food-art/02-niten-ichiryu.webp",
  "food-art/03-wellington-steak.png": "/art-optimized/food-art/03-wellington-steak.webp",
  "food-art/04-unconscious-mousse.png": "/art-optimized/food-art/04-unconscious-mousse.webp",
  "food-art/05-tricolor-icecream.png": "/art-optimized/food-art/05-tricolor-icecream.webp",
  "food-art/06-burnt-pudding.png": "/art-optimized/food-art/06-burnt-pudding.webp"
};
