import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

/**
 * Art-only image optimizer.
 *
 * User policy: art images may lose AT MOST 50% of their file size.
 * Therefore this script only emits a webp variant when the encoded
 * file is >= 50% of the original size; otherwise the page falls back
 * to the original asset.
 *
 * JPEGs already ship at a sensible size and lossless/lossy webp often
 * grows them, so they are intentionally left alone.
 *
 * Usage: npm run optimize-art
 * Output: public/art-optimized/** (assets) + src/utils/art-images.generated.ts (manifest)
 */
const root = process.cwd();
const folders = ["illustrations", "product-posters", "fashion-design", "food-art"];
const entriesRoot = path.join(root, "src/content/entries");
const outRoot = path.join(root, "public/art-optimized");
const manifestPath = path.join(root, "src/utils/art-images.generated.ts");

const minRatio = 0.5;
const images = [];

for (const folder of folders) {
  const dir = path.join(entriesRoot, folder);
  for (const filename of fs.readdirSync(dir)) {
    if (!/\.(png|jpe?g|webp)$/i.test(filename)) continue;
    if (filename === "cover.png") continue;
    images.push({ folder, filename, file: path.join(dir, filename) });
  }
}

fs.rmSync(outRoot, { recursive: true, force: true });
fs.mkdirSync(outRoot, { recursive: true });

const manifest = {};
let originalBytes = 0;
let emittedBytes = 0;
let emittedCount = 0;
const skipped = [];

for (const image of images) {
  const original = fs.readFileSync(image.file);
  const originalSize = original.length;
  originalBytes += originalSize;

  if (!/\.png$/i.test(image.filename)) {
    skipped.push(`${image.folder}/${image.filename} (non-PNG, kept original)`);
    continue;
  }

  const encoded = await sharp(original)
    .webp({ lossless: true, effort: 5 })
    .toBuffer();

  if (encoded.length < originalSize * minRatio) {
    skipped.push(
      `${image.folder}/${image.filename} (webp would be ${Math.round((encoded.length / originalSize) * 100)}% < 50%, kept original)`,
    );
    continue;
  }

  const outFolder = path.join(outRoot, image.folder);
  fs.mkdirSync(outFolder, { recursive: true });
  const outName = image.filename.replace(/\.png$/i, ".webp");
  fs.writeFileSync(path.join(outFolder, outName), encoded);

  const key = `${image.folder}/${image.filename}`;
  manifest[key] = `/art-optimized/${image.folder}/${outName}`;
  emittedBytes += encoded.length;
  emittedCount += 1;
}

const manifestSource = `// @generated by scripts/optimize-art.mjs — do not edit by hand.\n// Maps original art filenames to optimized public assets.\nexport const artImageMap: Record<string, string> = ${JSON.stringify(manifest, null, 2)};\n`;
fs.writeFileSync(manifestPath, manifestSource);

console.log(`Optimized ${emittedCount}/${images.length} art images.`);
console.log(`Original total: ${(originalBytes / 1024 / 1024).toFixed(2)} MB`);
console.log(`Emitted webp: ${(emittedBytes / 1024 / 1024).toFixed(2)} MB (lossless, each >= 50% of its original)`);
console.log(`Skipped: ${skipped.length}`);
for (const line of skipped) console.log(`  - ${line}`);
console.log(`Manifest written to ${path.relative(root, manifestPath)}`);
